version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  aws-ecs: circleci/aws-ecs@2.2.1
jobs:
  test-and-build:
    docker:
      - image: circleci/python:3.8
        environment:
          MIX_ENV: prod
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
         key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      # build and push Docker image
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

workflows:
  version: 2
  test-and-build:
    jobs:
      - test-and-build
      - aws-ecr/build-and-push-image:
          repo: "exstores_staging"
          tag: "${CIRCLE_BRANCH}_latest"
          requires:
            - test-and-build
          filters:
            branches:
              only:
                - main
                - develop
      - aws-ecs/deploy-service-update:
          name: deploy-development
          requires:
            - aws-ecr/build-and-push-image
          family: "api_service"
          cluster-name: "prod-cluster"
          service-name: "api_service"
          container-image-name-updates: "container=api_container,tag=${CIRCLE_BRANCH}_latest"
          filters:
            branches:
              only:
                - develop
      - aws-ecs/deploy-service-update:
          name: deploy-staging
          requires:
            - aws-ecr/build-and-push-image
          family: "exstores-staging-tsk"
          cluster-name: "exstores-cls-staging"
          service-name: "exstores-staging-service"
          container-image-name-updates: "container=exstores-staging-container,tag=${CIRCLE_BRANCH}_latest"
          filters:
            branches:
              only:
                - main
