version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@7.2.0
  aws-ecs: circleci/aws-ecs@2.2.1
jobs:
  test-and-build:
    docker:
      - image: circleci/python:3.8
        environment:
          MIX_ENV: prod
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
         key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      # build and push Docker image
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

workflows:
  version: 2
  test-and-build:
    jobs:
      - test-and-build
      - aws-ecr/build-and-push-image:
          repo: "python_rest_api"
          tag: "${CIRCLE_SHA1}"
          requires:
            - test-and-build
          filters:
            branches:
              only:
                - main
                - develop
      - aws-ecs/deploy-service-update:
          name: deploy-development
          requires:
            - aws-ecr/build-and-push-image
          family: "python_rest_api-service"
          cluster-name: "PythonRestApiProdClus"
          service-name: "python_rest_api-service"
          container-image-name-updates: "container=python_rest_api-service,tag=${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - develop
      - aws-ecs/update-service:
          name: deploy-staging
          requires:
            - aws-ecs/deploy-service-update
          family: "python_rest_api-service"
          cluster-name: "PythonRestApiProdClus"
          service-name: "python_rest_api-service"
          container-image-name-updates: "container=python_rest_api-service,tag=${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - main
      - approve-deploy:
          type: approval
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only:
                - main
      - aws-ecs/deploy-service-update:
          name: deploy-production
          requires:
            - approve-deploy
          family: "python_rest_api-service"
          cluster-name: "PythonRestApiProdClus"
          service-name: "python_rest_api-service"
          container-image-name-updates: "container=python_rest_api-service,tag=${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - main
